.PHONY: clean All

All:
	@echo "----------Building project:[ NTRU-PEKS - Debug ]----------"
	@"$(MAKE)" -f  "NTRU-PEKS.mk"
clean:
	@echo "----------Cleaning project:[ NTRU-PEKS - Debug ]----------"
	@"$(MAKE)" -f  "NTRU-PEKS.mk" clean
